language: node_js

services:
  - docker

node_js:
  - "8"

git:
  depth: 2

before_install:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - git checkout $BRANCH

install:
  - docker build -t dns-zone-test .travis-ci/
  - npm install
  - node build.js

script:
  - docker run --rm -v $TRAVIS_BUILD_DIR:/dns-zone-blacklist dns-zone-test

deploy:
  provider: script
  script: .travis-ci/deploy.sh
  skip_cleanup: true
  on:
    branch: master
